project:
    type: website
    output-dir: "docs"
    preview:
        port: 22222
        browser: true
        watch-inputs: true
        navigate: true

website:
    title: "PRiME"
    site-url: https://github.com/PRiME-Bath
    description: "Practice-based research group in mathematical sciences education and pedagogy"
    open-graph: true
    navbar:
        pinned: true
        left:
            - text: "People"
              href: people.qmd
            - text: "Seminars"
              href: seminars.qmd
            - text: "Teaching"
              href: teaching.qmd
            - text: "Projects"
              href: projects.qmd              
            - text: "Resources"
              href: resources.qmd
        right: 
            - icon: envelope
              aria-label: email   
              href: "mailto:PRiME@bath.ac.uk"
    page-footer: 
        left: "Department of Mathematical Sciences <br> PRiME Group" 
        border: false
        background: light
        right: | 
            ![](images/logo_white.png){width=25%}
    search: 
        location: navbar
        type: textbox
    back-to-top-navigation: true

format:
    html:
        theme: [pulse, styles.scss]
        grid:
            body-width: 1600px
        fontsize: 1.2rem
        toc: false
        code-link: true
        anchor-sections: true
        fig-cap-location: margin
        reference-location: margin
        footnotes-hover: true

editor: source